import tensorflow as tf
import numpy as np
import pandas as pd

#Loading/reading the .geo file that is generated by running the 2D-holes.python code. Use the location of your .geo file file. 

with open("/Users/shishirbarai/Desktop/Gmsh-TF/Gmsh-test-1.geo", "r") as f:
     data = f.readlines()
     parsed_data = []
for line in data:
     parsed_data.append(data)
      
matrix = np.array(parsed_data)
parsed_data
